# Generated by Django 5.1.6 on 2026-04-09 13:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BangDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_1', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Bài tập 1')),
                ('homework_2', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Bài tập 2')),
                ('homework_3', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Bài tập 3')),
                ('quiz_1', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Kiểm tra 1')),
                ('quiz_2', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Kiểm tra 2')),
                ('midterm_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Điểm giữa kỳ')),
                ('final_exam', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Điểm cuối kỳ')),
                ('attendance_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Tỷ lệ chuyên cần')),
                ('final_score', models.FloatField(default=0, help_text='= 0.2*homework_avg + 0.2*quiz_avg + 0.25*midterm + 0.35*final_exam', verbose_name='Điểm tổng kết')),
                ('performance_label', models.CharField(blank=True, choices=[('Weak', 'Yếu'), ('Average', 'Trung bình'), ('Good', 'Khá'), ('Excellent', 'Giỏi')], max_length=15, verbose_name='Xếp loại')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Bảng điểm',
                'verbose_name_plural': 'Bảng điểm',
                'db_table': 'bang_diem',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('vai_tro', models.CharField(choices=[('admin', 'Quản trị viên'), ('teacher', 'Giáo viên'), ('student', 'Học viên')], default='student', max_length=10, verbose_name='Vai trò')),
                ('ho_ten', models.CharField(blank=True, max_length=150, verbose_name='Họ tên')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'nguoi_dung',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DuDoanML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_label', models.CharField(choices=[('Weak', 'Yếu'), ('Average', 'Trung bình'), ('Good', 'Khá'), ('Excellent', 'Giỏi')], max_length=15, verbose_name='Dự đoán')),
                ('prob_weak', models.FloatField(default=0, verbose_name='% Yếu')),
                ('prob_average', models.FloatField(default=0, verbose_name='% Trung bình')),
                ('prob_good', models.FloatField(default=0, verbose_name='% Khá')),
                ('prob_excellent', models.FloatField(default=0, verbose_name='% Giỏi')),
                ('risk_level', models.CharField(choices=[('high_risk', 'Rủi ro cao'), ('medium_risk', 'Rủi ro trung bình'), ('low_risk', 'Rủi ro thấp'), ('no_risk', 'Không rủi ro')], default='no_risk', max_length=15, verbose_name='Mức rủi ro')),
                ('model_name', models.CharField(default='XGBoost', max_length=50, verbose_name='Model sử dụng')),
                ('predicted_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian dự đoán')),
                ('bang_diem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='du_doan', to='core.bangdiem', verbose_name='Bảng điểm')),
            ],
            options={
                'verbose_name': 'Dự đoán ML',
                'verbose_name_plural': 'Dự đoán ML',
                'db_table': 'du_doan_ml',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='HocVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hoc_vien', models.CharField(max_length=20, unique=True, verbose_name='Mã học viên')),
                ('ngay_sinh', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gioi_tinh', models.CharField(choices=[('nam', 'Nam'), ('nu', 'Nữ')], default='nam', max_length=5, verbose_name='Giới tính')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('nguoi_dung', models.OneToOneField(limit_choices_to={'vai_tro': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='hoc_vien', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Học viên',
                'verbose_name_plural': 'Học viên',
                'db_table': 'hoc_vien',
                'ordering': ['ma_hoc_vien'],
            },
        ),
        migrations.AddField(
            model_name='bangdiem',
            name='hoc_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bang_diem_list', to='core.hocvien', verbose_name='Học viên'),
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_lop', models.CharField(max_length=100, verbose_name='Tên lớp')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
                ('nam_hoc', models.CharField(default='2025-2026', max_length=20, verbose_name='Năm học')),
                ('hoc_ky', models.PositiveSmallIntegerField(default=1, verbose_name='Học kỳ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('giao_vien', models.ForeignKey(blank=True, limit_choices_to={'vai_tro': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lop_phu_trach', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'db_table': 'lop_hoc',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hocvien',
            name='lop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoc_vien_list', to='core.lophoc', verbose_name='Lớp học'),
        ),
    ]
